# Generated by Django 6.0.7 on 2026-07-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_summary_alter_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
    ]
