# Generated by Django 6.0.7 on 2026-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsive_image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/projects/'),
        ),
    ]
