# Generated by Django 6.0.7 on 2026-08-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_desktop_image_project_responsive_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('section_number', models.CharField(blank=True, max_length=10)),
                ('eyebrow', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('introduction', models.TextField(blank=True)),
                ('large_image', models.ImageField(blank=True, null=True, upload_to='portfolio/case_studies/')),
                ('large_image_alt', models.CharField(blank=True, max_length=255)),
                ('large_image_caption', models.CharField(blank=True, max_length=255)),
                ('small_image', models.ImageField(blank=True, null=True, upload_to='portfolio/case_studies/')),
                ('small_image_alt', models.CharField(blank=True, max_length=255)),
                ('small_image_caption', models.CharField(blank=True, max_length=255)),
                ('closing_label', models.CharField(blank=True, max_length=120)),
                ('closing_text', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_study_sections', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyExpandable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('number', models.CharField(blank=True, help_text='Optional. Leave empty for a standalone expandable.', max_length=10)),
                ('summary', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expandables', to='portfolio.casestudysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
