# Generated by Django 6.0.7 on 2026-08-04 13:51

from django.db import migrations, models


def create_default_contact_links(apps, schema_editor):
    ContactLink = apps.get_model("portfolio", "ContactLink")

    default_links = [
        {
            "label": "GitHub",
            "url": "https://github.com/1anamasiliuniene-netizen",
            "opens_in_new_tab": True,
            "order": 1,
        },
        {
            "label": "LinkedIn",
            "url": "https://www.linkedin.com/in/ana-masili%C5%ABnien%C4%97-0233903b5",
            "opens_in_new_tab": True,
            "order": 2,
        },
        {
            "label": "Email",
            "url": "mailto:1ana.masiliuniene@email.com",
            "opens_in_new_tab": False,
            "order": 3,
        },
        {
            "label": "Phone",
            "url": "tel:+370 67837541",
            "opens_in_new_tab": False,
            "order": 4,
        },
    ]

    for link in default_links:
        ContactLink.objects.get_or_create(
            label=link["label"],
            defaults=link,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_resumedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(help_text='Use a full URL, mailto: email link, or tel: phone link.', max_length=500)),
                ('opens_in_new_tab', models.BooleanField(default=True, help_text='Disable this for mailto: and tel: links.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RunPython(
            create_default_contact_links,
            migrations.RunPython.noop,
        ),
    ]
