# Generated by Django 6.0.7 on 2026-08-04 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_contactlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('issuer', models.CharField(blank=True, max_length=160)),
                ('file', models.FileField(upload_to='portfolio/certificates/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('is_active', models.BooleanField(default=False, help_text='Enable this when the certificate should appear on the resume page.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
