# Generated by Django 6.0.7 on 2026-08-04 14:10

from django.db import migrations, models


def populate_project_links(apps, schema_editor):
    Project = apps.get_model("portfolio", "Project")

    links_by_slug = {
        "a-terapija": {
            "live_url": "https://www.a-terapija.lt",
            "source_url": "https://github.com/1anamasiliuniene-netizen/A-Terapija.git",
        },
        "mini-notion": {
            "live_url": "https://mini-notion-anama.pythonanywhere.com/projects/",
            "source_url": "https://github.com/1anamasiliuniene-netizen/mini_notion",
        },
    }

    for slug, links in links_by_slug.items():
        Project.objects.filter(slug=slug).update(**links)


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_additionalcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, help_text='Optional live application URL shown on the project page.', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='source_url',
            field=models.URLField(blank=True, help_text='Optional GitHub or source code URL shown on the project page.', max_length=500),
        ),
        migrations.RunPython(
            populate_project_links,
            migrations.RunPython.noop,
        ),
    ]
