# Generated by Django 6.0.7 on 2026-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_seed_public_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudysection',
            name='large_image_allow_full_size',
            field=models.BooleanField(default=False, help_text='Enable for detailed diagrams or screenshots readers need to inspect.', verbose_name='Allow full-size viewing'),
        ),
        migrations.AddField(
            model_name='casestudysection',
            name='small_image_allow_full_size',
            field=models.BooleanField(default=False, help_text='Enable for detailed diagrams or screenshots readers need to inspect.', verbose_name='Allow full-size viewing'),
        ),
    ]
