# Generated by Django 6.0.7 on 2026-10-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_casestudysection_large_image_allow_full_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desktop_image_allow_full_size',
            field=models.BooleanField(default=False, verbose_name='Allow full-size viewing'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsive_image_allow_full_size',
            field=models.BooleanField(default=False, verbose_name='Allow full-size viewing'),
        ),
    ]
